# Generated by Django 3.2.3 on 2022-04-26 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncuestaSatisfaccion',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'EncuestaSatisfaccion',
                'db_table': 'Encuesta_Satisfaccion',
            },
        ),
        migrations.CreateModel(
            name='PreguntaSatisfaccion',
            fields=[
                ('pregunta_id', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.TextField()),
                ('respuesta', models.CharField(max_length=70)),
                ('encuesta_satisfaccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='encuestas.encuestasatisfaccion')),
            ],
            options={
                'verbose_name': 'PreguntaSatisfaccion',
                'db_table': 'Pregunta_Satisfaccion',
            },
        ),
    ]
