# Generated by Django 3.2.3 on 2022-05-03 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alumnoModel',
            fields=[
                ('alumno_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('a_paterno', models.CharField(max_length=150)),
                ('a_materno', models.CharField(max_length=150)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('correo', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'alumno',
                'db_table': 'alumno',
            },
        ),
        migrations.CreateModel(
            name='catalogoModel',
            fields=[
                ('id_catalogo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300)),
                ('pregunta', models.CharField(max_length=300)),
                ('opciones', models.CharField(max_length=300)),
                ('tipo', models.CharField(max_length=300)),
                ('orden', models.IntegerField()),
            ],
            options={
                'verbose_name': 'catalogo',
                'db_table': 'catalogo',
            },
        ),
        migrations.CreateModel(
            name='cursoModel',
            fields=[
                ('curso_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(max_length=300)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('resp_exsol', models.CharField(max_length=300)),
                ('contrato', models.CharField(max_length=100)),
                ('req_servicio', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'curso',
                'db_table': 'curso',
            },
        ),
        migrations.CreateModel(
            name='empresaModel',
            fields=[
                ('empresa_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=300)),
                ('nombre_responsable', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'empresa',
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='encuestaCursoModel',
            fields=[
                ('e_curso_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('curso_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='encuestas.cursomodel')),
            ],
            options={
                'verbose_name': 'EncuestaCurso',
                'db_table': 'encuesta_curso',
            },
        ),
        migrations.CreateModel(
            name='encuestaSatisfaccionModel',
            fields=[
                ('encuesta_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'EncuestaSatisfaccion',
                'db_table': 'Encuesta_Satisfaccion',
            },
        ),
        migrations.CreateModel(
            name='preguntaSatisfaccionModel',
            fields=[
                ('pregunta_id', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(max_length=250)),
                ('valor', models.CharField(max_length=250)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='encuestas.encuestasatisfaccionmodel')),
            ],
            options={
                'verbose_name': 'PreguntaSatisfaccion',
                'db_table': 'Pregunta_Satisfaccion',
            },
        ),
        migrations.CreateModel(
            name='preguntaCursoModel',
            fields=[
                ('pregunta_id', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(max_length=250)),
                ('valor', models.CharField(max_length=250)),
                ('encuesta_curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='encuestas.encuestacursomodel')),
            ],
            options={
                'verbose_name': 'PreguntaCurso',
                'db_table': 'pregunta_curso',
            },
        ),
        migrations.AddField(
            model_name='cursomodel',
            name='resp_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='encuestas.empresamodel'),
        ),
        migrations.CreateModel(
            name='alumnoCursoModel',
            fields=[
                ('al_cu_id', models.AutoField(primary_key=True, serialize=False)),
                ('alumno_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='encuestas.alumnomodel')),
                ('curso_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='encuestas.cursomodel')),
            ],
            options={
                'verbose_name': 'alumno_curso',
                'db_table': 'alumno_curso',
            },
        ),
    ]
