# Generated by Django 3.2.3 on 2022-05-09 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuestasatisfaccionmodel',
            name='curso',
        ),
    ]
