# Generated by Django 3.2.3 on 2022-05-18 01:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='encuestaRecepcionServicioModel',
            fields=[
                ('encuesta_recepcion_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'EncuestaRecepcionServicio',
                'db_table': 'encuesta_recepcion_servicio',
            },
        ),
        migrations.CreateModel(
            name='preguntaRecepcionServicioModel',
            fields=[
                ('pregunta_id', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(max_length=250)),
                ('valor', models.CharField(max_length=250)),
                ('orden', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('porcentaje', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.encuestarecepcionserviciomodel')),
            ],
            options={
                'verbose_name': 'PreguntaRecepcionServicio',
                'db_table': 'pregunta_recepcion_servicio',
            },
        ),
    ]
