# Generated by Django 3.2.3 on 2022-05-07 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnomodel',
            name='curso',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='encuestas.cursomodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumnomodel',
            name='rut',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumnomodel',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='encuestas.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preguntasatisfaccionmodel',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.encuestasatisfaccionmodel'),
        ),
    ]
