# Generated by Django 3.2.3 on 2022-05-18 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0002_encuestarecepcionserviciomodel_preguntarecepcionserviciomodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preguntarecepcionserviciomodel',
            old_name='encuesta',
            new_name='encuesta_recepcion',
        ),
    ]
