# Generated by Django 3.2.3 on 2022-05-09 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0002_remove_encuestasatisfaccionmodel_curso'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='encuestaCursoModel',
            new_name='encuestaAlumnoModel',
        ),
        migrations.RenameModel(
            old_name='preguntaCursoModel',
            new_name='preguntaAlumnoModel',
        ),
        migrations.RenameModel(
            old_name='respuestaCursoModel',
            new_name='respuestaAlumnoModel',
        ),
        migrations.AlterModelOptions(
            name='encuestaalumnomodel',
            options={'verbose_name': 'EncuestaAlumno'},
        ),
        migrations.AlterModelOptions(
            name='preguntaalumnomodel',
            options={'verbose_name': 'PreguntaAlumno'},
        ),
        migrations.AlterModelOptions(
            name='respuestaalumnomodel',
            options={'verbose_name': 'RespuestaAlumno'},
        ),
        migrations.AddField(
            model_name='encuestasatisfaccionmodel',
            name='nombre',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='encuestaalumnomodel',
            table='encuesta_alumno',
        ),
        migrations.AlterModelTable(
            name='preguntaalumnomodel',
            table='pregunta_alumno',
        ),
        migrations.AlterModelTable(
            name='respuestaalumnomodel',
            table='respuesta_alumno',
        ),
        migrations.CreateModel(
            name='cursoEncuestaModel',
            fields=[
                ('cur_enc_id', models.AutoField(primary_key=True, serialize=False)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='encuestas.cursomodel')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='encuestas.encuestasatisfaccionmodel')),
            ],
            options={
                'verbose_name': 'curso_encuesta',
                'db_table': 'curso_encuesta',
            },
        ),
    ]
