# Generated by Django 3.2.3 on 2022-05-08 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0002_auto_20220506_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumnocursomodel',
            old_name='alumno_id',
            new_name='alumno',
        ),
        migrations.RenameField(
            model_name='alumnocursomodel',
            old_name='curso_id',
            new_name='curso',
        ),
    ]
