# Generated by Django 3.2.3 on 2022-05-09 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0003_auto_20220508_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestasatisfaccionmodel',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='encuestas.cursomodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='respuestasatisfaccionmodel',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.encuestasatisfaccionmodel'),
        ),
    ]
