# Generated by Django 3.2.3 on 2022-05-08 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0003_auto_20220507_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encuestacursomodel',
            old_name='curso_id',
            new_name='curso',
        ),
        migrations.CreateModel(
            name='respuestaCursoModel',
            fields=[
                ('respuesta_id', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(max_length=250)),
                ('respuesta', models.CharField(max_length=250)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='encuestas.alumnomodel')),
                ('e_curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='encuestas.encuestacursomodel')),
            ],
            options={
                'verbose_name': 'RespuestaCurso',
                'db_table': 'respuesta_curso',
            },
        ),
    ]
