# Generated by Django 3.2.3 on 2022-05-09 02:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0004_auto_20220508_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntasatisfaccionmodel',
            name='orden',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
