# Generated by Django 3.2.3 on 2022-05-18 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0004_respuestarecepcionserviciomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='cursoEncuestaRecepcionServicioModel',
            fields=[
                ('curso_encuesta_recepcion_id', models.AutoField(primary_key=True, serialize=False)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.cursomodel')),
                ('encuesta_recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.respuestarecepcionserviciomodel')),
            ],
            options={
                'verbose_name': 'curso_encuesta_recepcion_servicio',
                'db_table': 'curso_encuesta_recepcion_servicio',
            },
        ),
    ]
