# Generated by Django 3.2.3 on 2022-05-09 02:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0005_alter_preguntasatisfaccionmodel_orden'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursomodel',
            old_name='resp_cliente',
            new_name='empresa',
        ),
        migrations.AlterField(
            model_name='preguntasatisfaccionmodel',
            name='orden',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
