# Generated by Django 3.2.3 on 2022-05-09 23:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0007_auto_20220508_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respuestasatisfaccionmodel',
            old_name='respuesta',
            new_name='respuesta_texto',
        ),
        migrations.AddField(
            model_name='respuestasatisfaccionmodel',
            name='respuesta_valor',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
