# Generated by Django 3.2.3 on 2022-05-22 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0007_auto_20220518_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestaalumnomodel',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='encuestas.cursomodel'),
            preserve_default=False,
        ),
    ]
