# Generated by Django 3.2.3 on 2022-05-22 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0008_respuestaalumnomodel_curso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preguntaalumnomodel',
            old_name='encuesta_curso',
            new_name='encuesta_alumno',
        ),
    ]
