# Generated by Django 3.2.3 on 2022-05-29 00:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0009_rename_encuesta_curso_preguntaalumnomodel_encuesta_alumno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntarecepcionserviciomodel',
            name='porcentaje',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='preguntarecepcionserviciomodel',
            name='valor',
            field=models.CharField(choices=[('Deficiente,Malo,Regular,Bueno,Excelente', 'Deficiente,Malo,Regular,Bueno,Excelente'), ('Si,No', 'Si,No'), ('Muy insatisfecho,Insatisfecho,Ni satisfecho ni insatisfecho,Satisfecho,Muy satisfecho', 'Muy insatisfecho,Insatisfecho,Ni satisfecho ni insatisfecho,Satisfecho,Muy satisfecho'), ('No aplica,Cumple,Parcialmente,No cumple', 'No aplica,Cumple,Parcialmente,No cumple'), ('Observacion', 'Observacion')], max_length=250),
        ),
        migrations.AlterField(
            model_name='respuestaalumnomodel',
            name='encuesta_alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.encuestaalumnomodel'),
        ),
    ]
