# Generated by Django 3.2.3 on 2022-05-11 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0009_respuestasatisfaccionmodel_orden_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestasatisfaccionmodel',
            name='respuesta_texto',
            field=models.CharField(blank=True, default='0', max_length=250),
        ),
        migrations.AlterField(
            model_name='respuestasatisfaccionmodel',
            name='respuesta_valor',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
