# Generated by Django 3.2.3 on 2022-05-11 01:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0010_auto_20220510_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumnocursomodel',
            old_name='al_cu_id',
            new_name='alumno_curso_id',
        ),
        migrations.RenameField(
            model_name='encuestaalumnomodel',
            old_name='enc_curso_id',
            new_name='encuesta_alumno_id',
        ),
        migrations.RemoveField(
            model_name='encuestaalumnomodel',
            name='alumno_curso',
        ),
        migrations.RemoveField(
            model_name='respuestaalumnomodel',
            name='respuesta',
        ),
        migrations.AddField(
            model_name='encuestaalumnomodel',
            name='nombre',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respuestaalumnomodel',
            name='alumno_curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='encuestas.alumnocursomodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respuestaalumnomodel',
            name='orden_respuesta',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respuestaalumnomodel',
            name='respuesta_texto',
            field=models.CharField(blank=True, default='0', max_length=250),
        ),
        migrations.AddField(
            model_name='respuestaalumnomodel',
            name='respuesta_valor',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumnocursomodel',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.alumnomodel'),
        ),
        migrations.AlterField(
            model_name='alumnocursomodel',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.cursomodel'),
        ),
        migrations.AlterField(
            model_name='preguntaalumnomodel',
            name='orden',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
