# Generated by Django 3.2.3 on 2022-05-29 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0010_auto_20220528_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntaalumnomodel',
            name='valor',
            field=models.CharField(choices=[('Deficiente,Malo,Regular,Bueno,Excelente', 'Deficiente,Malo,Regular,Bueno,Excelente'), ('Si,No', 'Si,No'), ('Muy insatisfecho,Insatisfecho,Ni satisfecho ni insatisfecho,Satisfecho,Muy satisfecho', 'Muy insatisfecho,Insatisfecho,Ni satisfecho ni insatisfecho,Satisfecho,Muy satisfecho'), ('No aplica,Cumple,Parcialmente,No cumple', 'No aplica,Cumple,Parcialmente,No cumple'), ('Observacion', 'Observacion')], max_length=250),
        ),
        migrations.AlterField(
            model_name='preguntasatisfaccionmodel',
            name='valor',
            field=models.CharField(choices=[('Deficiente,Malo,Regular,Bueno,Excelente', 'Deficiente,Malo,Regular,Bueno,Excelente'), ('Si,No', 'Si,No'), ('Muy insatisfecho,Insatisfecho,Ni satisfecho ni insatisfecho,Satisfecho,Muy satisfecho', 'Muy insatisfecho,Insatisfecho,Ni satisfecho ni insatisfecho,Satisfecho,Muy satisfecho'), ('No aplica,Cumple,Parcialmente,No cumple', 'No aplica,Cumple,Parcialmente,No cumple'), ('Observacion', 'Observacion')], max_length=250),
        ),
    ]
