# Generated by Django 3.2.3 on 2022-05-11 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0011_auto_20220510_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnomodel',
            name='nombre_completo',
        ),
    ]
