# Generated by Django 3.2.3 on 2022-05-11 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0012_remove_alumnomodel_nombre_completo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cursoEncuestaModel',
            new_name='cursoEncuestaSatisfaccionModel',
        ),
        migrations.AlterModelOptions(
            name='cursoencuestasatisfaccionmodel',
            options={'verbose_name': 'curso_encuesta_satisfaccion'},
        ),
        migrations.AlterModelTable(
            name='cursoencuestasatisfaccionmodel',
            table='curso_encuesta_satisfaccion',
        ),
    ]
