# Generated by Django 3.2.3 on 2022-05-11 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0013_auto_20220510_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursoencuestasatisfaccionmodel',
            old_name='cur_enc_id',
            new_name='curso_encuesta_id',
        ),
    ]
