# Generated by Django 3.2.3 on 2022-05-11 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0014_rename_cur_enc_id_cursoencuestasatisfaccionmodel_curso_encuesta_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='cursoEncuestaAlumnoModel',
            fields=[
                ('curso_encuesta_alumno_id', models.AutoField(primary_key=True, serialize=False)),
                ('curso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='encuestas.cursomodel')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.encuestaalumnomodel')),
            ],
            options={
                'verbose_name': 'curso_encuesta_alumno',
                'db_table': 'curso_encuesta_alumno',
            },
        ),
    ]
