# Generated by Django 3.2.3 on 2022-05-12 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0015_cursoencuestaalumnomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursoencuestaalumnomodel',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.cursomodel'),
        ),
        migrations.AlterField(
            model_name='cursoencuestaalumnomodel',
            name='encuesta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='encuestas.encuestaalumnomodel'),
        ),
    ]
