# Generated by Django 3.2.3 on 2022-05-12 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0016_auto_20220511_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursoencuestaalumnomodel',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.encuestaalumnomodel'),
        ),
    ]
