# Generated by Django 3.2.3 on 2022-05-12 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0017_alter_cursoencuestaalumnomodel_encuesta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respuestaalumnomodel',
            old_name='encuesta_curso',
            new_name='encuesta_alumno',
        ),
        migrations.AlterField(
            model_name='preguntaalumnomodel',
            name='encuesta_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.encuestaalumnomodel'),
        ),
    ]
